# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f0a415338ae5157f0bd5037d8c71871f78c3e6ba6d7e2f1ec1969266beac2898fbb66a01418d2aabff1fc2ddbd12d57bbfa2ffd73622c432fa55b231b9fcd04

test:
  secret_key_base: dfbe9e91eb7b6a32128696686631aa9bc4af0adc978e9c70fb11a356b132a30c3c5531e31ce3127436a1715c7279d5e081a0fbe255bc3cb9a1e962b981a706ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
